/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'formpanel',
                id: 'pnlForm',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'txtName',
                        label: 'name',
                        name: 'name'
                    },
                    {
                        xtype: 'button',
                        id: 'btnSave',
                        itemId: 'mybutton',
                        text: 'Save'
                    },
                    {
                        xtype: 'label',
                        height: 277,
                        html: 'empty',
                        id: 'lblName'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton1',
                        text: 'Show values from store'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton2',
                        text: 'load store from localstorage'
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton3',
                        text: 'Clear Localstorage'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onBtnSaveRelease',
                event: 'release',
                delegate: '#btnSave'
            },
            {
                fn: 'onMybutton1Release',
                event: 'release',
                delegate: '#mybutton1'
            },
            {
                fn: 'onMybutton2Release',
                event: 'release',
                delegate: '#mybutton2'
            },
            {
                fn: 'onMybutton3Release',
                event: 'release',
                delegate: '#mybutton3'
            }
        ]
    },

    onBtnSaveRelease: function(button, e, eOpts) {
        var values = Ext.getCmp("pnlForm").getValues();

        var store = Ext.getStore("Store1");


        var item = Ext.create('model.UserSettings', {
            id: 1,
            name: 'user name',
            value: values.name
        });

        item={name:'username',value:values.name}

        console.log(item.data);

        store.add(item);

        //store.add({name:'aliiiiiii'});
        store.sync();
    },

    onMybutton1Release: function(button, e, eOpts) {
        var store = Ext.getStore("Store1");

        //clear lbl
        Ext.getCmp("lblName").setHtml("");

        for(var c=0;c < store.getCount();c++)
        {
            var record = store.getAt(c);
            var value=record.data.value;
            var temp=Ext.getCmp("lblName").getHtml();
            Ext.getCmp("lblName").setHtml(value + "<br/>" + temp);

        }



    },

    onMybutton2Release: function(button, e, eOpts) {
        var store = Ext.getStore("Store1");

        store.load({
            callback: function(records, operation, success) {
                // the operation object contains all of the details of the load operation
                console.log(records);

                for(f in records)
                {
                    console.log(records[f].data);
                }

            },
            scope: this
        });
    },

    onMybutton3Release: function(button, e, eOpts) {
        localStorage.clear();
    }

});